// MediaPlayerObserver.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/mojom/media_player.mojom
//

package org.chromium.media.mojom;


public interface MediaPlayerObserver extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends MediaPlayerObserver, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<MediaPlayerObserver, MediaPlayerObserver.Proxy> MANAGER = MediaPlayerObserver_Internal.MANAGER;


    void onMutedStatusChanged(
boolean muted);



    void onMediaPositionStateChanged(
org.chromium.media_session.mojom.MediaPosition mediaPosition);



    void onMediaSizeChanged(
org.chromium.gfx.mojom.Size size);



    void onPictureInPictureAvailabilityChanged(
boolean available);



    void onAudioOutputSinkChangingDisabled(
);



    void onBufferUnderflow(
);



    void onSeek(
);


}
