// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// This file is autogenerated by
//     chrome/android/features/create_stripped_java_factory.py
// Please do not change its content or use it in actual code (DO NOT SUBMIT).

package org.chromium.chrome.browser.password_check;

import org.chromium.components.browser_ui.settings.SettingsLauncher;

public class PasswordCheckFactory {
    static public PasswordCheck getOrCreate (SettingsLauncher settingsLauncher) { return null; }
    static public void destroy () { return ; }
    static public void setPasswordCheckForTesting (PasswordCheck passwordCheck) { return ; }
    static public PasswordCheck getPasswordCheckInstance () { return null; }
}
