
// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../weblayer/public/navigation.h

package org.chromium.weblayer_private;

import android.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ImplNavigationState.WAITING_RESPONSE, ImplNavigationState.RECEIVING_BYTES,
    ImplNavigationState.COMPLETE, ImplNavigationState.FAILED
})
@Retention(RetentionPolicy.SOURCE)
public @interface ImplNavigationState {
  /**
   * Waiting to receive initial response data.
   */
  int WAITING_RESPONSE = 0;
  /**
   * Processing the response.
   */
  int RECEIVING_BYTES = 1;
  /**
   * The navigation succeeded. Any NavigationObservers would have had NavigationCompleted() called.
   */
  int COMPLETE = 2;
  /**
   * The navigation failed. This could be because of an error (in which case IsErrorPage() will
   * return true) or the navigation got turned into a download (in which case IsDownload() will
   * return true). NavigationObservers would have had NavigationFailed() called.
   */
  int FAILED = 3;
}
