
// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../weblayer/browser/controls_visibility_reason.h

package org.chromium.weblayer_private;

import android.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ImplControlsVisibilityReason.FULLSCREEN, ImplControlsVisibilityReason.FIND_IN_PAGE,
    ImplControlsVisibilityReason.TAB_MODAL_DIALOG, ImplControlsVisibilityReason.ACCESSIBILITY,
    ImplControlsVisibilityReason.ANIMATION, ImplControlsVisibilityReason.RENDERER_UNAVAILABLE,
    ImplControlsVisibilityReason.OTHER, ImplControlsVisibilityReason.REASON_COUNT
})
@Retention(RetentionPolicy.SOURCE)
public @interface ImplControlsVisibilityReason {
  /**
   * Browser controls are hidden when fullscreen is active.
   */
  int FULLSCREEN = 0;
  /**
   * Find in page forces browser controls to be visible.
   */
  int FIND_IN_PAGE = 1;
  /**
   * Tab modal dialogs obscure the content while leaving controls interactive.
   */
  int TAB_MODAL_DIALOG = 2;
  /**
   * If accessibility is enabled, controls are forced shown.
   */
  int ACCESSIBILITY = 3;
  /**
   * Browser controls visibility can be set to force them to animate in/out when being set or
   * cleared.
   */
  int ANIMATION = 4;
  /**
   * If the renderer isn't able to update the controls position because it is being destroyed,
   * crashed, or is unresponsive, show the controls.
   */
  int RENDERER_UNAVAILABLE = 5;
  /**
   * Miscellaneous reasons for showing the controls, including: * User entering text * The URL being
   * dangerous or having a warning * An interstitial is showing * chrome:// URL
   */
  int OTHER = 6;
  int REASON_COUNT = 7;
}
