// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// This file is autogenerated by
//     chrome/android/features/create_stripped_java_factory.py
// Please do not change its content or use it in actual code (DO NOT SUBMIT).

package org.chromium.chrome.browser.video_tutorials;

import android.content.Context;
import android.util.Pair;
import android.view.ViewStub;
import androidx.recyclerview.widget.RecyclerView;
import org.chromium.base.Callback;
import org.chromium.base.supplier.Supplier;
import org.chromium.chrome.browser.image_fetcher.ImageFetcher;
import org.chromium.chrome.browser.profiles.Profile;
import org.chromium.chrome.browser.video_tutorials.iph.VideoIPHCoordinator;
import org.chromium.chrome.browser.video_tutorials.iph.VideoTutorialTryNowTracker;
import org.chromium.chrome.browser.video_tutorials.list.TutorialListCoordinator;
import org.chromium.chrome.browser.video_tutorials.player.VideoPlayerCoordinator;
import org.chromium.components.embedder_support.view.ContentView;
import org.chromium.content_public.browser.WebContents;

public class VideoTutorialServiceFactory {
    static public VideoTutorialService getForProfile (Profile profile) { return null; }
    static public VideoIPHCoordinator createVideoIPHCoordinator (ViewStub viewStub, ImageFetcher imageFetcher, Callback<Tutorial> onClickListener, Callback<Tutorial> onDismissListener) { return null; }
    static public VideoPlayerCoordinator createVideoPlayerCoordinator (Context context, VideoTutorialService videoTutorialService, Supplier<Pair<WebContents,ContentView>> webContentsFactory, LanguageInfoProvider languageInfoProvider, Callback<Tutorial> tryNowCallback, Runnable closeCallback) { return null; }
    static public TutorialListCoordinator createTutorialListCoordinator (RecyclerView recyclerView, VideoTutorialService videoTutorialService, ImageFetcher imageFetcher, Callback<Tutorial> clickCallback) { return null; }
    static public VideoTutorialTryNowTracker getTryNowTracker () { return null; }
    static public void setVideoTutorialServiceForTesting (VideoTutorialService provider) { return ; }
}
