// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

public interface SelectOptionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autofill_assistant.SelectOptionProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The drop down element on which to select an option.
   * </pre>
   *
   * <code>optional .autofill_assistant.SelectorProto element = 2;</code>
   * @return Whether the element field is set.
   */
  boolean hasElement();
  /**
   * <pre>
   * The drop down element on which to select an option.
   * </pre>
   *
   * <code>optional .autofill_assistant.SelectorProto element = 2;</code>
   * @return The element.
   */
  org.chromium.chrome.browser.autofill_assistant.proto.SelectorProto getElement();

  /**
   * <pre>
   * Value of the option to use.
   * </pre>
   *
   * <code>.autofill_assistant.TextFilter text_filter_value = 7;</code>
   * @return Whether the textFilterValue field is set.
   */
  boolean hasTextFilterValue();
  /**
   * <pre>
   * Value of the option to use.
   * </pre>
   *
   * <code>.autofill_assistant.TextFilter text_filter_value = 7;</code>
   * @return The textFilterValue.
   */
  org.chromium.chrome.browser.autofill_assistant.proto.TextFilter getTextFilterValue();

  /**
   * <pre>
   * A value from an Autofill source. Note that this must be preceded by a
   * |CollectUserDataAction|.
   * </pre>
   *
   * <code>.autofill_assistant.AutofillValueRegexp autofill_value = 8;</code>
   * @return Whether the autofillValue field is set.
   */
  boolean hasAutofillValue();
  /**
   * <pre>
   * A value from an Autofill source. Note that this must be preceded by a
   * |CollectUserDataAction|.
   * </pre>
   *
   * <code>.autofill_assistant.AutofillValueRegexp autofill_value = 8;</code>
   * @return The autofillValue.
   */
  org.chromium.chrome.browser.autofill_assistant.proto.AutofillValueRegexp getAutofillValue();

  /**
   * <code>optional .autofill_assistant.SelectOptionProto.OptionComparisonAttribute option_comparison_attribute = 6;</code>
   * @return Whether the optionComparisonAttribute field is set.
   */
  boolean hasOptionComparisonAttribute();
  /**
   * <code>optional .autofill_assistant.SelectOptionProto.OptionComparisonAttribute option_comparison_attribute = 6;</code>
   * @return The optionComparisonAttribute.
   */
  org.chromium.chrome.browser.autofill_assistant.proto.SelectOptionProto.OptionComparisonAttribute getOptionComparisonAttribute();

  public org.chromium.chrome.browser.autofill_assistant.proto.SelectOptionProto.ValueCase getValueCase();
}
