// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dom_action.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

public interface WaitForDocumentToBecomeCompleteProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autofill_assistant.WaitForDocumentToBecomeCompleteProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .autofill_assistant.ClientIdProto client_id = 1;</code>
   * @return Whether the clientId field is set.
   */
  boolean hasClientId();
  /**
   * <code>optional .autofill_assistant.ClientIdProto client_id = 1;</code>
   * @return The clientId.
   */
  org.chromium.chrome.browser.autofill_assistant.proto.ClientIdProto getClientId();

  /**
   * <code>optional int32 timeout_in_ms = 2;</code>
   * @return Whether the timeoutInMs field is set.
   */
  boolean hasTimeoutInMs();
  /**
   * <code>optional int32 timeout_in_ms = 2;</code>
   * @return The timeoutInMs.
   */
  int getTimeoutInMs();
}
