// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// This file is autogenerated by
//     chrome/android/features/create_stripped_java_factory.py
// Please do not change its content or use it in actual code (DO NOT SUBMIT).

package org.chromium.components.browser_ui.bottomsheet;

import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import org.chromium.base.Callback;
import org.chromium.base.supplier.Supplier;
import org.chromium.components.browser_ui.widget.scrim.ScrimCoordinator;
import org.chromium.ui.KeyboardVisibilityDelegate;
import org.chromium.ui.base.WindowAndroid;

public class BottomSheetControllerFactory {
    static public ManagedBottomSheetController createBottomSheetController (Supplier<ScrimCoordinator> scrim, Callback<View> initializedCallback, Window window, KeyboardVisibilityDelegate keyboardDelegate, Supplier<ViewGroup> root) { return null; }
    static public void attach (WindowAndroid windowAndroid, ManagedBottomSheetController controller) { return ; }
    static public void detach (ManagedBottomSheetController controller) { return ; }
    static public void setExceptionReporter (Callback<Throwable> reporter) { return ; }
}
